### ISSUE TITLE
As an attendee, I would like to be able to buy badges for other people besides myself

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/rams#10]
Point of discussion: Although this functionality is included in RAMS, the wording surrounding badge ownership is MAGFest-specific and we should review it to make sure it's acceptable for MFF.

**Comment by jmdawson** [comment]
We need to see that verbiage to evaluate it. Where do we find it?

**Comment by ianlayton** [comment]
It is our practice that the person that purchases the badge has owner ship of the badge and can request that it is canceled or transferred.

**Comment by kitsuta** [comment]
@jmdawson That's, uh, a good question. Let me poke around and I'll get back to you on that.

**Comment by ianlayton** [comment]
@kitsuta I'm kinda torn on letting that happen because then it brings up issues with someone buying a badge for someone else, then transferring it and the first person coming to con thinking they have a badge waiting for them. I don't see this happening often, but we had an issue two years ago where someone purchased a badge for their partner of the time, then they had a falling out and wanted to transfer it. As normal, I send an email out to the person being affected as a notice, and it got into a little bit of a heated discussion with them as they claimed they gave the person money for the badge, blah blah blah. I'd rather deal with that over email and give a warning to person then it happen silently then it pop up at con.

**Comment by jmdawson** [comment]
Current status? Can we disable badge transfers? I think I saw a variable for that. If Rama is ok with taking on the admin burden of handling these through email (or service desk...) and executing transfer manually, that's fine with me. More features can be iceboxed.  Currently a person can fill in info for someone else and enter their own card, and I think we can work with that.

**Comment by kitsuta** [comment]
Yup, you can disable this. Just set `transferable_badge_types` to an empty string, i.e., `transferable_badge_types = ','`.

**Comment by jmdawson** [comment]
@ianlayton Is this what we want? Fully disable badge transfers?

**Comment by jmdawson** [comment]
I fixed this ...Tuesday.
