### ISSUE TITLE
Data in one database transaction carrying over to another

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#105]
Looking at the database transactions (Admin side; `People `-> `Feed of Database Changes`), I see that some fields from a previous database transaction (Victoria Earl, 13:23 April 26 2017) seem to have carried over into my transaction in some form (Scott Fuller, 19:40 April 26, 2017). These fields include ec_name ("Victoria Earl", which appears in the VE transaction as "me") and badge_printed_name ("Earl" in my transaction, blank in the previous transaction). This data seems to later be overridden with correct info, but it probably should never be there to begin with.

**Comment by kitsuta** [comment]
@SkylerRingtail My real address and phone number was in that screenshot so I removed it from the issue. That's really my bad -- I shouldn't use form fill on staging servers out of laziness. :x

The good news is that the system is not munging data. The bad news is that the FODC table is just so utterly unusable that you thought it was. The rows are (apparently) centered vertically, so that data for each entry starts _well above_ the `unpaid_preregistration` flag. If you highlight the text, you can see the tiny line break a little easier. Also for some reason the data starts with payment_method and ec_name, which is a little unexpected since EC info is far down the prereg form.

I'll consider this an issue to make the table readable by humans. MAGFest complains about this too.
