### ISSUE TITLE
(!!!) Registration completion screen can reveal and modify other attendees' information

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#117]
This is a serious issue.

The final "Registration Complete" screen shows a list of all preregistrations made from "this computer." This information appears to be based on a browser cookie. If an attendee registers from, for example, a public computer that isn't configured to purge cookies, this screen would reveal the real name of other attendees who registered at that computer AND also provide their confirmation link. That confirmation link would then allow access to view and modify the registration information of other attendees (including real names, phone numbers, and address information), and also allow transferring a badge.

I see no reason for providing this information. If an attendee needs to modify their own registration, they should refer to the e-mail they received or contact our staff.

As a separate issue, it seems like we give quite a lot of power to someone that has a confirmation link, or manages to guess one. For security reasons, should we not have some additional authentication (e.g. enter the code sent with your e-mail confirmation to access this form)?

**Comment by kitsuta** [comment]
>If an attendee registers from, for example, a public computer that isn't configured to purge cookies, this screen would reveal the real name of other attendees who registered at that computer AND also provide their confirmation link.
Just FYI, the pre-reg page and at-door reg pages are totally separate -- one of the differences is that there's no confirmation page in the at-door workflow. So an attendee would have to register from a public computer on their own time during pre-reg for this to be a concern. And then, uh, ANOTHER attendee would have to register from the same computer before it gets shut down/refreshed for the night. So while this is indeed technically possible, it's also incredibly unlikely -- to the point where with 20,000 badges purchased for MAGFest 2017, no one's badge was compromised.
 
> I see no reason for providing this information.
I'd say "This isn't a concern for MAGFest largely because we collect a lot less PII" but the confirmation links here were actually a feature request by Anthrocon, who collected much the same information MFF does. As for the reason -- emails in general are not very reliable (largely because attendees themselves will typo them), so we kept it in MAGFest because it gave attendees a quick and easy way to confirm their badge did in fact exist.

This all being said, we can hide this if desired. 

>As a separate issue, it seems like we give quite a lot of power to someone that has a confirmation link, or manages to guess one.
Randomly-generated UUID4 ids are not guessable. But yeah, the ability to have additional authentication is on the long-term to-do list, and using 2FA in the email was one of the ideas. That issue is logged here: https://github.com/magfest/ubersystem/issues/2346

**Comment by jmdawson** [comment]
The current behavior is acceptable to MFF for 2017. Changing this behavior is outside the scope of our current efforts.

**Comment by jmdawson** [comment]
Going to close this issue, as the work on accounts should resolve the majority of the concern.  As above, accounts is not in scope for 2017.

**Comment by ianlayton** [comment]
While not an issue for preregistration, this needs to be addressed for on site registration.

**Comment by jmdawson** [comment]
As stated above, it is not an issue with on-site registration, as this behavior is not repeated in on-site mode. MAGFest has run quite a few events w/ on-site reg under this system, and that particular issue is well-addressed.
