### ISSUE TITLE
One Day badges exist in addition to Per-day badges.

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#180]
There is a one-day type which seems to have at least one correct price on it ($25). If I select a badge specific to a day, forex Friday, the price is set at the current attendee price.
<img width="301" alt="screen shot 2017-10-27 at 18 40 57" src="https://user-images.githubusercontent.com/910490/32128800-a3ae44ec-bb46-11e7-9039-68028b650028.png">

**Comment by jmdawson** [comment]
Related, what are Thursday and Monday badges? I didn't define them in single_day section.

Badge definitions as follow:
`[badge_prices]
initial_attendee = 50
group_discount = 0
[[single_day]]
Friday = 25
Saturday = 35
Sunday = 25
[[attendee]]
"2017-10-01" = 55
"2017-11-30" = 60`

**Comment by jmdawson** [comment]
This error occurs whether I have set the epoch and eschaton dates to this weekend or not, and occur when at_the_con = True.

**Comment by ianlayton** [comment]
We don't use Thursday and Monday badges, so they can be removed if possible.

**Comment by kitsuta** [comment]
Per-day badges are generated automatically based on the epoch and eschaton dates. The prices you set will be applied to the corresponding day; for any day you DON'T set, it uses the "default_single_day" price, which is defined as $40 in configspec.ini.

The fact that you have the Thursday and Monday badges means that your config has epoch on a Thursday and eschaton on a Monday... the epoch and eschaton are meant to be literally only the event dates. The code does account for setup and teardown shifts and such outside of these dates, so you shouuuuldn't need to artificially extend the event dates. At_the_con mode is irrelevant in this case.

As for one days being there too... that's actually by design. It's kind of messy, but the per-day badges are generated using the "One Day" badge as their template. The one day badge is only in the dropdown for admins, and shouldn't be shown on the admin page.

The prices sound that they're not behaving as expected, so that, I can look into.

**Comment by kitsuta** [comment]
Oh, as an additional note, the "One Day" badge type will use the attendee's registration date to calculate the price. So if your attendee registered on a Friday, and you give them a "one day" badge, their badge price will be the Friday badge price ($25).

All the pricing stuff seems to work on my end, so I'll talk to @jmdawson about what exactly he's experiencing with the badge prices not being correct.

**Comment by jmdawson** [comment]
I was seeing $55 listed as the badge price when I selected a Friday Badge.

**Comment by jmdawson** [comment]
Because Panels seems to rely on Epoch and Eschaton for scheduling, and Programming asked to have access to the rest of Sunday, I extended the eschaton to 0000 on 'Monday.' Similarly, I set the Epoch to Thursday, because I think we needed something then, too.

**Comment by kitsuta** [comment]
Ohhhh right, panels. Yes, 'panels only happening during the event' is kind of a paradigm of the system. Probably our best bet is to edit the panels plugin to extend those times, so we can have epoch and eschaton set correctly.

**Comment by jmdawson** [comment]
Can we just set programming_start and programming_end variables in panels, then?

**Comment by kitsuta** [comment]
Yup, and this is in fact that next thing I'll work on.
