### ISSUE TITLE
Minor pricing

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#198]
I thought I heard there was a way to automate discount for different age groups. For example, minors between 12 and 6 get half price memberships for standard and daily badges.

If it's not already implemented, it's fine. Staff is use to manually updating minor prices.

If this is not already a feature, this may be a good 2018 wish list item.

**Comment by kitsuta** [comment]
There is a way to add age discounts! I'll want to test it before I say it's easy, to see if it works properly with, e.g., the badge upgrades.

**Comment by ianlayton** [comment]
It's extremely rare that we get a sponsoring minor that fall into the discount range, I think it's come up maybe once in the 6 years I've run reg. Even the minor discount isn't used a lot. Last year, out of around 7000 badges, we had

17 free kids (under 6)
17 full weekend discounts
13 Saturday discounts
6 Sunday discounts

So if it works, it works. If not, it's not a whole lot that my staff have to deal with.

For reference

Minor discounts (6 - 12 year olds), basically half off:
Full weekend: $30
Friday: $15
Saturday: $25
Sunday: $15
(I'm double checking what I put on the signage for the daily prices, but I'm fairly certain that these are correct)

Minors under 6 are free for weekend and dailys

If you can't do straight prices for it, 50% discount will work too.

**Comment by kitsuta** [comment]
OK, this was doable. Under-6 badges were already free, and I've added custom discounts for under-13 badges.

The price on the staging server (once it's redeployed) will be slightly off for attending badges until Nov 30, because the price we set is based on a discount, and right now attending badges are still $55. However, I made the discount only apply during the event, so this shouldn't be a problem.
