### ISSUE TITLE
Minor badge pricing

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#219]
I got a few reports during the event of the minor discount for those between 6 and 12 weren't working correctly. I did have to refund a person because the operator didn't catch that the discount wasn't applied correctly and it was on a daily badge. Beyond that refund, I don't know if it actually was occurring and/or if it was just occurring for the daily badges. I did test the full weekend attendee badge before the event and it was working correctly in rams.test

**Comment by kitsuta** [comment]
This is intended behavior -- age discounts aren't applied to non-weekend badges by default.

It's easy to change, but we'll need to decide exactly how to change it. Should minors get a set price, regardless of badge type? Should the minor discount apply to all types of badges? If so, does that include Sponsor and Shiny Sponsor, or just the full weekend and the daily badges? Are 'minor' badges actually their own separate badge type, so that minors technically would never have daily badges?

**Comment by ianlayton** [comment]
Half price for minors for standard membership, Friday, Saturday and Sunday. Full price for sponsor or shiny. 

If we need a set price, $32.00 Full weekend, $12.00 Friday, $20 Saturday, $12.00 Sunday. (To keep needing coins down)

They are the same badge type, just reduced price for that badge type.
