### ISSUE TITLE
As a registration or dealer staffer, I'd like the text of emails updated for 2019 as well as pricing information

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#304]
These are the standard text changes to emails plus updates to pricing information.  Will need to get additional information from the heads of Registration and Dealers.

**Comment by kitsuta** [comment]
Some extra related info, since I know we're onboarding some more people: Email templates can easily be viewed by respective department heads here: http://rams.test.furfest.org/rams/emails/pending using the standard staging login information.

If there's no emails of a type to be sent, it will show the raw template, which includes Jinja2 variables that are (hopefully) fairly self-explanatory. Many emails don't actually need to be edited, as the dates and prices update automatically when the relevant config options are updated, but because it's best practice to review the text _anyway_ we require most emails to be approved by an admin before they are actually activated. You can also "unapprove" emails, which deactivates them so that no more are sent.

**Comment by jmdawson** [comment]
Also I have largely completed these. Most of the requested changes are actually reflected in variable changes, and there were a very, very few actual tweaks to templates.
