### ISSUE TITLE
As a Registration staffer, it would be nice if a user could be checked in right from the Attendee Data page, so we can check in attendees faster

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#310]
Frequently, if a search hits only one user, RAMS takes you directly to the Attendee Data page. Also, if a user needs to pay, and we need to record that payment, that's also done via the Attendee Data page. However, to finalize their checkin, we have to go to the search page and click the checkin button. With the strong possibility of using unique barcodes to pull up attendee data this year, it would be exceptionally helpful - and reduce the number of clicks and pages that staff has to interact with - to have a checkin button right in the Attendee Data page. You're already looking at the person, why do we have to go back to search to finish checking them in?

**Comment by kitsuta** [comment]
According to [this line](https://github.com/MidwestFurryFandom/rams/blob/mff-staging/uber/site_sections/registration.py#L93), the Attendee Details page should not be returned like this while the server is in at-con mode (specifically for this reason!). It's not possible to override page handlers via other plugins, and you can't check people in without being in at-con mode, so I have no idea how that was happening -- definitely should test it at some point and make sure it really does do what I think it does.

The Attendee details page is not the intended workflow for taking payment -- IIRC the intended workflow (the "[Recent At-Door Registrations](http://rams.test.furfest.org/rams/registration/new)" page) was bypassed because the timer on that page was removing at-door registrations before people got to the front of the line (there _is_ a version of that page that shows all at-door registrations, not sure why that wasn't used but there's some possible totally sensible reasons).

Of course none of this means we can't add check-in button to the details page, but it wouldn't be that much more difficult to just, for example, add payment fields to the regular check-in box and let people bypass that page entirely. Or we could do both!

By the way, check-in barcodes are already implemented, so as long as you'll have the readers we can definitely turn that on.

**Comment by kitsuta** [comment]
Just as a general update, our profiling of the app has found that the "Recent At-Door Registrations" page is abysmally slow. We already added payment workflow to the regular check-in modal via https://github.com/MidwestFurryFandom/rams/pull/364, so we're also going to add the check-in modal to the attendee data page just to make everything go a little faster.
