### ISSUE TITLE
As an attendee, I'd like to be able to check in with a bar code instead of having a registration staffer look me up by ID, so I can check in faster

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#311]
Implement bar code for registration (I think this is something that is already baked in and just needs to be activated?)

Attendees would really only need to print their confirmation w/bar code prior to arrival with this feature.

**Comment by kitsuta** [comment]
Yup, that feature flag is called `use_checkin_barcode`. Some notes on how it works:

- We generate an Aztec 2D barcode that contains a UUID4 value that corresponds to the attendee's registration, called `public_id` in the code. Unlike `id`, this ID is not used in any URLs, and will take you directly to that registration when you search for it on the admin side.
- Once the feature is turned on, we show the barcode on the attendee's registration confirmation page. There's also an email (which will need approval) called "Check in faster at {EVENT_NAME}" that shows them their code, _However..._
- Due to limitations with our email-sending library, it is not possible for us to embed images in emails -- the image they receive in email calls a function on the server that generates and renders the barcode. MAGFest has never had a problem with this that I'm aware of, but obviously it's not ideal if we're trying to _reduce_ our network usage.

As a side note, the "barcode" folder under /uber has nothing to do with the check-in 2D barcodes.

**Comment by ianlayton** [comment]
If this is a just a flag and email template...can this be handled quickly enough to go live for reg open? If not, that is okay at this point

**Comment by ianlayton** [comment]
Ah...never mind on that request...just read the templated email and didn't realize it was a batch email that went out at a different time then registration.

**Comment by DarkKilauea** [comment]
Closed as this is already implemented
