### ISSUE TITLE
As a Registration staffer, I'd like to be able to process a credit card payment for an attendee right from the Attendee Data page, so I can process payments faster

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/rams#312]
Right now, when an agent goes to process a credit card on behalf of an attendee, they have to click the "register themselves" link, and then process the payment as if they were the user. Additionally, this also requires that the agent either right click and open as new window (which leaves the possibility of mistakes being made if they don't close the window), or it drops them out of the Agent view of RAMS and into the client view, which necessitates the usage of the back button or going back to the RAMS admin home page and navigating back to the user's profile page, and verifying the registration is complete, then following the process to finalize checking the   user in. While we're updating the profile page to allow for checkins directly from that page, can we also make it so that we can process credit card payments directly from the profile page, with a return to the profile page   instead of being dropped into the attendee experience? It likely will mean a second credit card processing workflow, but it will literally save minutes on each checkin.

**Comment by kitsuta** [comment]
As you may have guessed from my comment on #310, the reason this workflow is so awful is that this is _very_ much not how you are supposed to do this. If it amuses you (i.e., this is not at all a criticism of reg), please imagine me basically having a heart attack when I found out this was what folks ended up doing, because... yes, that _is_ several extra minutes per check-in.

I don't know where the communication on this broke down -- I changed some stuff in the Recent At-Door Registrations page to accommodate MFF using Stripe as their only payment processor (the default is to use a phone-based payment method, like Square) so I was sure at the time that I'd done my part telling people how to do things! I know that it is very difficult to stop and text people about things in the middle of a rush, so I was also on standby during the first part of reg. Perhaps I left too early, or people didn't think they could ask me things, but... oh my gosh, definitely ask me things!

In any case, I can indeed probably route Stripe payments through the check-in dialog. It... _should_ be pretty straightforward. If not, we can make the At-Door reg page work better for MFF so they can actually use it!

**Comment by kitsuta** [comment]
Effectively fixed by https://github.com/MidwestFurryFandom/rams/pull/364, which does this but on the search page.
