### ISSUE TITLE
Creating staffer via "Add an attendee" creates a staffer that is flagged as a volunteer, even when checkbox is unchecked

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#342]
When I create a staffer via "Add an attendee," the "Want to Volunteer?" checkbox is left blank (and as a consequence, the personal phone number is not required). However, later opening this registration either as an admin from the attendee list or as the attendee (via register themself) shows the checkbox checked. This was noticeable because changes are not allowed to be saved if a volunteer is missing a personal phone number. It is unclear why the data being saved and displayed is **different than what was originally entered.**

**Comment by SkylerRingtail** [comment]
Possibly related to behavior seen in #344, where staffers are being treated as a special category of volunteer.

**Comment by SkylerRingtail** [comment]
This is resulting in weird situations where a staff member can end up as both attendee and staff:

![image](https://user-images.githubusercontent.com/28108495/62995541-a05d1400-be26-11e9-8c77-095215d1d140.png)

**Comment by kitsuta** [comment]
The "want to volunteer" checkbox is not a checkbox for volunteers, but rather a checkbox for _volunteering_, It must always be checked if someone is working as either volunteer or staff -- it's what enables all the staffing/volunteering-related system features for that attendee.

The unexpected behavior described here is a result of the system adjusting flags to match selections an admin made, without forcing that admin to go through and make everything sync up. So if you create an attendee with a Staff badge, the system sees that and guesses that you also want their staffing/volunteering flag to be checked (which... you do!).

#344 is just a wording issue -- MAGFest historically does not make a strong distinction between volunteers and staff -- and has no bearing on the backend. Actually, that checkbox used to say "I want to volunteer for [EVENT]" even for people with staff badges until one MAGLabs where several staff from a contract group unchecked the box and accidentally removed their own Staff badge. 😬 

As for the dual ribbons, this is another automated adjustment that just doesn't take into account the fact that MFF uses Staff ribbons instead of badges. Easy to override in the plugin.

Not checking the phone number -- good catch! This would also be the root cause of https://github.com/MidwestFurryFandom/rams/issues/345. We're running our validation checks before those automatic flag adjustments, so staffing/volunteering attendees are getting through without a comped reason or phone number. I'll track fixing the phone number under #345, and fixing the dual ribbons under this issue.

**Comment by jmdawson** [comment]
We can update the term to "I want to volunteer for <EVENT>" for the checkbox.
