### ISSUE TITLE
Marketplace Payment Page shows a larger value than expected

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#358]
https://github.com/MidwestFurryFandom/rams/blob/4993f8e75aca2b4b30cc06de30244b623f537c22/uber/templates/marketplace/edit.html#L14

An attendee has reported to us that the page says they owe $240, but the fee is only $75. I checked on their account, and they have a waitlisted dealers room application which was valued at $315, a panel in the art show ($10), and this outstanding marketplace app. I suspect this is a conflict between Artist Marketplace process and Dealer's Room process.
<img width="783" alt="Screen Shot 2019-10-27 at 13 54 04" src="https://user-images.githubusercontent.com/910490/67639728-4914fe80-f8c1-11e9-9f38-1e71303ca30a.png">

**Comment by jmdawson** [comment]
Ok, more info: They upgraded to a sponsor along the way, and while the attendee record indicates they paid, that's not reflected in the amount owed on their attendee record.

**Comment by kitsuta** [comment]
Is the badge in question part of the dealers room application? Those badges typically don't see a payment button until they're approved, so the system doesn't actually differentiate between "amount owed for waitlisted app" and "amount owed for approved app." In other words, it will still believe they owe the $315 despite being waitlisted. $240 is $315 - $75 -- I can't be sure this is the issue because I don't have access to see the badge in question but that's my best guess.

If the badge is in a dealers group, you should be able to resolve this by removing them from that group (remember to also change their "paid" status from "paid by group" to, presumably, "yes").

The long term fix would possibly be to make the system aware of their dealer application status, but... If you don't take them out of the dealer group at some point they might be able to use the extra badges in said group. I'm not sure.

**Comment by jmdawson** [comment]
The badge was disassociated w/ the group which got credit for the attendee's payment for their upgraded sponsor badge.
<img width="770" alt="Screen Shot 2019-10-27 at 14 03 29" src="https://user-images.githubusercontent.com/910490/67639836-bf663080-f8c2-11e9-914e-91b6fb01ab15.png">

**Comment by jmdawson** [comment]
Attendee updated 02:37 on August 01 2019 Benjamin Cook badge_type=''Attendee' -> 'Sponsor''
Group updated 02:37 on August 01 2019 Benjamin Cook cost='315 -> 405'
Attendee updated 02:38 on August 01 2019 Benjamin Cook badge_status=''New' -> 'Complete'', admin_notes=''' -> 'Payment ID <REDACTED> $150'', print_pending='False -> True'
Group updated 02:39 on August 01 2019 Benjamin Cook amount_paid='0 -> 150', tables='Decimal('1') -> '1''

**Comment by kitsuta** [comment]
Just to clarify, a "yes" payment status doesn't indicate that they're fully paid now, just that they were at one point fully paid. So if they've only paid for a base badge but chose a sponsor upgrade later, their paid field will still say "yes." This is partly because you can decide to un-upgrade until you've paid for it.

When you have time we should discuss the details of this case over telegram so we can figure out exactly what the system thinks the badge owes the $240 for

**Comment by jmdawson** [comment]
The amount makes sense, too: $240: 75+150+15 => 1 Marketplace Slot, 1 Sponsor Badge, 1 Table in the art show.
