### ISSUE TITLE
As an admin, when I visit the people-attendees page, i see none

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#51]
I have to click on the 1 link to show the list.
![noattendees](https://cloud.githubusercontent.com/assets/910490/25032215/f0d03900-2097-11e7-9aab-bc0645a64679.jpeg)

**Comment by kitsuta** [comment]
Notes: the problem here is that the page sets you up to _expect_ a list of attendees and then just doesn't load them. The reasoning behind this is solid enough -- the "I want to search for an attendee" use-case is much more common than "I want to see 100 attendees sorted by name," and the latter is a performance hit -- but the UX was never really designed to make the intentions here clear.
