### ISSUE TITLE
Inconsistency with how user is notified about problematic fields

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#95]
Some field errors are appearing as a top-of-page banner after attempting to submit info (e.g. an incorrect phone number or a missing country). Other fields, such as the "Name on ID" field, have an in-field notice. These seem like they should have a consistent style (I'd lean towards the in-field one). Compare:

![mff banner notice](https://cloud.githubusercontent.com/assets/28108495/25568142/4b1fc5b0-2dc2-11e7-9ad3-a15d579bcd70.png)

-----

![mff id required field](https://cloud.githubusercontent.com/assets/28108495/25568143/4f4a97fa-2dc2-11e7-9500-eb784433532a.png)

**Comment by kitsuta** [comment]
While this is a totally valid UX complaint, it may have to stay this way for the time being. The different notifications are because most of our checks are done server-side, where we check various things about the attendee vs what they put in the form (for example, when an admin creates an attendee, most fields aren't required). We CAN recreate that logic in the template, but the template's JS is extremely brittle as it is -- trying to do so would invite even more UX issues, like fields being required when they shouldn't be.

The "Name on ID" field being a clientside check is because that checkbox about the legal name being the same as your full name is fake -- there's no database field associated with it. By the time we get to the model validations, we don't know the state of that checkbox anymore.

**Comment by jmdawson** [comment]
Stale. We can reopen if it's still an issue, but will probably stay less important than other things forever, unless someone wants to work on a PR privately.
