### ISSUE TITLE
Order of data validation does not match order on page

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/rams#96]
Checks for missing info don't appear to occur in the same order as they do on the page. For example, the "Name on ID" field seems to be the first one checked, before the "First Name" and "Last Name" fields.

**Comment by ianlayton** [comment]
Actually...something else I noticed is that it seems to only do error checking up to the point where an error occurs. It then shows that error, then stops checking. Long term, it would be more efficient if all error checking was done at once and the user was shown all issues instead of just the first one it runs across.

**Comment by kitsuta** [comment]
I can fix the order, but unfortunately the additional UX issue of errors not being collected and displayed all at once is due to limitations of our error messaging system. We can file a separate issue for that for the Icebox.
